### ISSUE TITLE
Compliling error for macOS M1

### ISSUE THREAD

**Issue by jianshu93** [hcdenbakker/sepia#20]
Dear sepia team

SIMD support for M1 seems to be fail. May be I will come back later when SIMD libraries support M1 chip.

Many Thanks,

Jianshu

**Comment by hcdenbakker** [comment]
Dear Jianshu,
Thanks for letting us know. I haven't had the opportunity yet to compile sepia on a M1 Mac (it works for Intel Macs), so this is very helpful.
-Henk

**Comment by sirselim** [comment]
@jianshu93 - it might be worth trying the latest build (updated a day ago). I was unable to compile on arm64 based devices (#21) and @hcdenbakker pushed a patch and now sepia builds completely and works well on the Nvidia Jetson boards that we are using. It may be that resolves the issue for M1 based Macs as well.

**Comment by jianshu93** [comment]
Many thanks！

**Comment by jianshu93** [comment]
Hello Team,

I can successfully compile it on M1 Pro.

Many thanks,

Jianshu

**Comment by hcdenbakker** [comment]
Awesome! This was a relatively simple fix fortunately. I will close this issue for now.
