### ISSUE TITLE
Memory mapped index

### ISSUE THREAD

**Issue by Midnighter** [hcdenbakker/sepia#22]
Looks like a great project, I look forward to trying it out!

I was wondering if you have plans to support the memory-mapped option that kraken2 provides? That means keeping the built index file in a memory mounted filesystem. This has been very useful to me since it avoids the time consuming step of loading a large index file into memory and it allows multiple kraken2 processes to share the same file in memory rather than introducing their own copy thus allowing better memory management.

Thanks for the info!

**Comment by hcdenbakker** [comment]
Hi, 
I do have plans to support the memory-mapped option that kraken2 provides. I am not sure of a time line for this though.

-Henk
